export const USE_CASES = [
  {
    id: 'food-delivery',
    label: 'Food Delivery',
    hook: 'A native, secure handoff layer for the apps you already use.',
    icon: 'pod-sealed',
    audiences: [
      'Urban and suburban delivery app users',
      'Apartment dwellers and high-density housing',
      'Meal kit subscribers',
    ],
    color: '--color-primary',
  },
  {
    id: 'roommate-dorm',
    label: 'Roommate & Dorm',
    hook: 'Your personal territory lock inside shared living spaces.',
    icon: 'shield-check',
    audiences: [
      'College students in dorms',
      'Young adults in shared apartments',
      'Co-living and sublet residents',
      'Parents of students',
    ],
    color: '--color-nfc',
  },
  {
    id: 'childproof',
    label: 'Childproof Storage',
    hook: 'Smarter than clunky child locks. Cleaner than cabinet latches.',
    icon: 'verified',
    audiences: [
      'Parents with toddlers or infants',
      'Families in small homes or apartments',
      'Caregivers and babysitters',
    ],
    color: '--color-confirm',
  },
  {
    id: 'firearm',
    label: 'Firearm Security',
    hook: 'Quick access. Responsible control. Smart safety.',
    icon: 'lock',
    audiences: [
      'Gun owners with families',
      'First-time firearm buyers',
      'Safety-conscious households',
      'Firearm retailers and training programs',
    ],
    color: '--color-deep',
  },
  {
    id: 'car-trunk',
    label: 'Car Trunk',
    hook: 'A mobile vault buckled in and locked to your vehicle.',
    icon: 'location',
    audiences: [
      'Urban drivers',
      'Gig workers — Uber, DoorDash drivers',
      'Travelers with luggage',
      'Car accessory retailers',
    ],
    color: '--color-primary',
  },
  {
    id: 'boat-outdoor',
    label: 'Boat & Outdoor',
    hook: 'Weather-resistant security for unpredictable environments.',
    icon: 'pod-open',
    audiences: [
      'Boat owners and marina users',
      'RV and camper owners',
      'Outdoor sports enthusiasts',
      'Marine supply retailers',
    ],
    color: '--color-nfc',
  },
  {
    id: 'travel-hotel',
    label: 'Travel & Hotel',
    hook: 'Bring your own safe. Light enough for any trip.',
    icon: 'chain-of-custody',
    audiences: [
      'Frequent travelers',
      'Hostel and Airbnb users',
      'Digital nomads',
      'Travel gear brands',
    ],
    color: '--color-amber',
  },
  {
    id: 'package-theft',
    label: 'Package Security',
    hook: "An app-connected delivery endpoint that thieves can't touch.",
    icon: 'nfc',
    audiences: [
      'Suburban homeowners and frequent online shoppers',
      'Amazon, Shopify, and DTC buyers',
      'High package-theft neighborhoods',
      'E-commerce and last-mile delivery partners',
    ],
    color: '--color-deep',
  },
  {
    id: 'workplace',
    label: 'Workplace',
    hook: 'A flexible personal locker for open-plan and shared offices.',
    icon: 'biometric',
    audiences: [
      'Corporate employees in open-plan spaces',
      'Retail workers without secure backroom storage',
      'Coworking space members',
      'Employers offering security perks',
    ],
    color: '--color-confirm',
  },
  {
    id: 'gym-fitness',
    label: 'Gym & Fitness',
    hook: 'Portable, hygienic, and yours. Better than any gym locker.',
    icon: 'mascot',
    audiences: [
      'Gym members and boutique fitness users',
      'College recreation centers',
      'Personal trainers and athletes',
      'Gym chains and fitness studios',
    ],
    color: '--color-primary',
  },
];
